apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xmyv
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xmyv
    app.kubernetes.io/part-of: tkrw-pr712-0075-0072-app
  name: devfile-sample-xmyv
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xmyv
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xmyv
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0072-tenant/tkrw-pr712-0075-0072-app/devfile-sample-xmyv@sha256:e781b5730594ecf02988b2b99fa6d855ae34a7f32a37fef9bc1ecbe6c61e3a9f
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
